"""add status, vibes, rating to media_items

Revision ID: 7413da11b8ba
Revises: 6ccecf2342cf
Create Date: 2025-09-06 22:09:36.196001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7413da11b8ba'
down_revision = '6ccecf2342cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('vibes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_items', schema=None) as batch_op:
        batch_op.drop_column('rating')
        batch_op.drop_column('vibes')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
